#!/bin/bash
#  ██                                            
# ░██              ██████                        
# ░██       ██████░██░░░██ ███     ██ ██████████ 
# ░██████  ██░░░░ ░██  ░██░░██  █ ░██░░██░░██░░██
# ░██░░░██░░█████ ░██████  ░██ ███░██ ░██ ░██ ░██
# ░██  ░██ ░░░░░██░██░░░   ░████░████ ░██ ░██ ░██
# ░██████  ██████ ░██      ███░ ░░░██ ███ ░██ ░██
# ░░░░░   ░░░░░░  ░░      ░░░    ░░░ ░░░  ░░  ░░ 


#---Autostart---#
feh --bg-scale /home/riz/Pictures/papes/reunion.png
~/.config/polybar/launch.sh
~/.config/bspwm/script.sh
sxhkd &

#---BSPWM---#
bspc monitor -d     戮 ﭮ

bspc config border_width         5
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

#---Colours---#
bspc config normal_border_color \#6272a4
bspc config focused_border_color \#bd93f9
bspc config presel_feedback_color \#bd93f9

#---Rules---#
bspc config external_rules_command ~/.config/bspwm/external_rules
bspc rule -a firefox desktop=
bspc rule -a firefox:Toolkit state=floating sticky=on
bspc rule -a Steam desktop=戮
bspc rule -a Lutris desktop=戮
bspc rule -a discord desktop=ﭮ
bspc rule -a Zathura state=tiled
bspc rule -a osu!.exe desktop=
bspc rule -a kitty desktop=
