#!/bin/bash

wid=$1
class=$2
instance=$3
consequences=$4
title=$(xtitle "$wid")

if [ "$class" = "Steam" ]; then
  if [ "$title" = "Friends List" ]; then
    echo "split_dir=east"
    echo "split_ratio=0.7"
  else
    echo "split_dir=south"
    echo "split_ratio=0.5"
  fi
fi
